### ISSUE TITLE
Calling mock in void context can't trigger unmock() in DESTROY()

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/mock-sub#10]
This is because we throw away the object/class, so there's nowhere to store the sub ref.

**Comment by jberger** [comment]
Of course you could make the behavior of `mock` context specific (ie, set `keep` if called in void context) but I'd argue that at that point all you are doing is monkey patching and you've used a sledgehammer to do it. YMMV

**Comment by stevieb9** [comment]
I've decided to remove the documentation that shows void context use, and put a blurb in the docs to not use void context.
