### ISSUE TITLE
called_with before being called will error

### ISSUE THREAD

**Issue by jberger** [stevieb9/mock-sub#8]
since `called_with` relies on the internal data being an array reference, if it is called when the mock has not yet been called it will die with an error.

``` bash
perl -MMock::Sub -E 'sub hi {} my $mock = Mock::Sub->new(sub => "hi"); $mock->called_with'
```

simply adding a `|| []` would fix this, or else throwing some other exception like "mock not yet called" would be an alternative.

**Comment by stevieb9** [comment]
Fixed in d14ba6a, called_with() now die()s if its called before the mocked sub has been.
